name: 'amplify-preview-actions'
description: 'This action builds and deploys your AWS Amplify pull request preview for public repository'
inputs:
  branch_name:
    description: 'GitHub branch name to deploy'
    required: true
  display_name:
    description: 'Display name'
    required: true
  amplify_command:
    description: 'amplify command: SUPPORTED: [deploy, delete]'
    required: true
  comments_url:
    description: 'Github comments url'
    default: "${{ github.event.pull_request.comments_url }}"
    required: false

runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.branch_name }}
    - ${{ inputs.amplify_command }}
    - ${{ inputs.comments_url }}
    - ${{ inputs.display_name }}

branding:
  icon: 'git-pull-request'
  color: 'blue'
